version: 2.1

jobs:
  lint-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - app-dir: ~/Projects/udapeople/frontend
      - run: npm i
      - run: npm run lint
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - app-dir: ~/Projects/udapeople/backend
      - run: npm i
      - run: npm run build
workflows:
  build-test:
    jobs:
      - lint-frontend
      - build-backend
