#Created by Rafael Castro Gonzalez
version: 2.1

orbs:
  slack: circleci/slack@3.4.2

commands:
  auto-destruct-env:
    description: Destroy the entire infrastructure
    steps:
      - run:
          name: Delete all files from the current S3 bucket
          command: |
            if aws s3api head-bucket --bucket udapeople-${ID}
            then
              aws s3 rm s3://udapeople-${ID}/ --recursive
            fi
          when: on_fail
      - run:
          name: Delete the current CloudFormation stacks
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

  revert-migration:
    description: Revert the last migration
    steps:
      - checkout
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            DATA_MIGRATIONSTATUS=$(curl -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request GET https://api.memstash.io/values/migration_completion_<< pipeline.id >>)
            echo ${DATA_MIGRATIONSTATUS}
            if [[ ${DATA_MIGRATIONSTATUS} == 1 ]]
            then
              cd backend
              npm i
              npm audit fix --audit-level=critical --force
              npm run migrations:revert
            fi
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build application frontend
          command: |
            cd frontend
            npm i
            npm run build
      #- slack/status:
          #fail_only: true
            
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build application backend
          command: |
            cd backend
            npm i
            npm run build
      #- slack/status:
          #fail_only: true
            
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm i
            npm i jest-junit
            npm run test -- --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/reports/junit/
      - store_test_results:
          path: /tmp/reports/junit/     
      #- slack/status:
          #fail_only: true
          
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test backend
          command: |
            cd backend
            npm i
            npm install jest-junit
            npm run test -- --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/reports/junit/
      - store_test_results:
          path: /tmp/reports/junit/
      #- slack/status:
          #fail_only: true
            
  analyze-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Analyze and resolve frontend dependencies
          command: |
            cd frontend
            npm i
            npm audit fix --audit-level=critical
      #- slack/status:
          #fail_only: true            
            
  analyze-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Analyze and resolve backend dependencies
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical
      #- slack/status:
          #fail_only: true
            
  deploy-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum -y install tar gzip
      - run:
          name: Get OldWorkflowID and save it to https://memstash.io/
          command: |
            export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
            echo ${OldWorkflowID}  
            if [ -n "$OldWorkflowID" ]
            then
              curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data ${OldWorkflowID} https://api.memstash.io/values/old_workflowID
            else 
              echo "No old infrastructure exists for UdaPeople"
            fi
            
      - run:
          name: deploy backend infra
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="backend-deployment-${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: deploy frontend infra
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Add Backend EC2 Instance IP to inventory
          command: |
            aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - auto-destruct-env
      #- slack/status:
          #fail_only: true 

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            apk add --no-cache openssh-client
            apk add --no-cache --upgrade bash
            pip install awscli
      - add_ssh_keys:
          fingerprints: ["0b:f0:04:ba:01:e9:18:d0:78:b4:48:93:6d:fc:9a:22"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm
            pip install awscli
      - run:
          name: Add env file
          command: |
            echo "TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> backend/.env
            echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> backend/.env
            echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> backend/.env
            echo "TYPEORM_HOST=${TYPEORM_HOST}" >> backend/.env
            echo "TYPEORM_PORT=${TYPEORM_PORT}" >> backend/.env
            echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> backend/.env
            echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> backend/.env
            echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> backend/.env
            echo "ENVIRONMENT=${ENVIRONMENT}" >> backend/.env
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            tar -czvf ../../backend.tar.gz ../../backend
            ansible-playbook -i inventory.txt main.yml        
      - auto-destruct-env
      #- slack/status:
          #fail_only: true

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run migrations and save status to https://memstash.io/
          command: |
            cd backend
            npm install
            npm run migrations > migrations.txt
            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT \
            --data $( grep -c "No migrations are pending" migrations.txt ) \
            https://api.memstash.io/values/migration_completion_<< pipeline.id >>
      #- slack/status:
          #fail_only: true

  deploy-frontend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache tar
            apk add --no-cache gzip
            apk add --no-cache ansible
            apk add --no-cache nodejs
            apk add --no-cache npm
            apk add --no-cache bash
            pip install awscli
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL=$API_URL" >> frontend/.env
            echo "${API_URL}"
      - run:
          name: "Baking backend API_URL into the front-end"
          command: |
            npm install webpack-dev-server -g
            cd frontend
            npm i
            npm run build      
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID}".tar.gz dist
      - run: 
          name: Copy built frontend files to the S3 bucket
          command: |
            aws s3 cp ./frontend/dist s3://udapeople-${ID} --recursive  
      - revert-migration
      - auto-destruct-env
      #- slack/status:
          #fail_only: true

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            apk add --update bash
            pip install awscli
      - run:
          name: Smoke test backend
          command: |
            export BACKEND_IP=$(aws ec2 --region us-west-2 describe-instances \
                  --filters Name=instance-state-name,Values=running Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
                  --output text)
            echo ${BACKEND_IP}
            APP_URL="http://${BACKEND_IP}:3030/api/status"
            echo ${APP_URL}
            curl ${APP_URL}
      - run:
          name: Smoke test frontend
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employee"
            if curl -s ${URL} | grep "Welcome"
            then
              return 0
            else
              return 1
            fi
      - revert-migration
      - auto-destruct-env
      #- slack/status:
          #fail_only: true 
                      
  deploy-cloudfront:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0b:f0:04:ba:01:e9:18:d0:78:b4:48:93:6d:fc:9a:22"]
      - run:
          name: Install dependencies
          command: |
            apk add --update nodejs npm curl bash
            pip install awscli
      - run:
          name: Update cloudfront distribution
          command: |
            export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name=='WorkflowID'].Value" --no-paginate --output text)
            export STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
            echo Old Workflow Id: "${OldWorkflowID}"
            echo Stacks: "${STACKS}"
            aws cloudformation update-stack  \
              --stack-name udapeople-cloudfront-${OldWorkflowID} \
              --template-file .circleci/files/cloudfront.yml \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople
            
            if [ -n "${OldWorkflowID}" ] && [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              echo "Delete old infrastructure"
              if aws s3api head-bucket --bucket udapeople-${OldWorkflowID}
              then
                aws s3 rm s3://udapeople-${OldWorkflowID}/ --recursive
              fi
              aws cloudformation delete-stack --stack-name cloud-devops-frontend-${OldWorkflowID}
              aws cloudformation delete-stack --stack-name cloud-devops-backend-${OldWorkflowID}
            fi          
      - auto-destruct-env
      #- slack/status:
          #fail_only: true

workflows:
  udapeople:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - analyze-frontend:
          requires: [build-frontend]
      - analyze-backend:
          requires: [build-backend]
      - deploy-infra:
          requires: [test-frontend, test-backend, analyze-frontend, analyze-backend]
          filters:
            branches:
              only:
                - master
      - deploy-backend:
          requires: [deploy-infra]
          filters:
            branches:
              only:
                - master
      - deploy-frontend:
          requires: [deploy-backend]
          filters:
            branches:
              only:
                - master          
      - smoke-test:
          requires: [deploy-frontend]
          filters:
            branches:
              only:
                - master
      - deploy-cloudfront:
          requires: [smoke-test]
          filters:
            branches:
              only:
                - master