version: 2.1

jobs:
  build-frontend:
    working_directory: ~/Projects/udapeople/frontend
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build
  build-backend:
    working_directory: ~/Projects/udapeople/backend
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build
workflows:
  build-test:
    jobs:
      - build-frontend
      - build-backend