#Created by Rafael Castro Gonzalez
version: 2.1

commands:
  npm-install:
    parameters:
      end:
        type: string
    steps:
      - run: 
          name: Install << parameters.end >> dependencies
          command: |
            cd << parameters.end >>
            npm i
  destroy-environment:
    steps:
      - run:
          name: Destroy backend
          command: |
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
      - run:
          name: Destroy frontend
          command: |
            aws s3 rm s3://udapeople-frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7} --recursive
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

  revert-migrations:
    steps:
      - run:
          name: install backend dependencies
          command: |
            cd backend
            npm i
          when: on_fail
      - run:
          name: Revert database migration if it has already ran
          command: |
            if curl -H "token: ae63d41c-2e4e-40c1-9e30-4a2a3e3cdb95" --request GET https://api.memstash.io/values/${CIRCLE_WORKFLOW_ID:0:7} | grep "true"
            then 
              cd backend
              npm run migrations:revert
            else 
              echo "no revert migration needed"
            fi
          when: on_fail


orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  build-frontend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: frontend
      - run: 
          name: Building Frontend
          command: | 
            cd frontend && npm run build
      #- slack/notify-on-failure

  build-backend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: backend
      - run: 
          name: Building Backend
          command: |
            cd backend && npm run build
      - run:
          name: Copy backend for Ansible
          command: |
              mkdir /tmp/saveme
              cp ./backend/package.json /tmp/saveme/
              cd backend
              tar -zcvf /tmp/saveme/backend.tar.gz ./
              ls -l /tmp/saveme/backend.tar.gz
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - backend.tar.gz
            - package.json
      #- slack/notify-on-failure

  test-frontend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: "frontend"
      - run:
          name: Test Frontend
          command: |
            cd frontend
            mkdir -p ./reports/junit/
            npm install --save-dev jest-junit jest-junit-reporter
            ./node_modules/.bin/jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
      - store_test_results:
          path: ./frontend/reports/junit/
      #- slack/notify-on-failure

  test-backend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: "backend"
      - run:
          name: Test Backend
          command: |
            cd backend
              mkdir -p ./reports/junit/
              npm install --save-dev jest-junit jest-junit-reporter
              ./node_modules/.bin/jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
      - store_test_results:
          path: ./backend/reports/junit/
      #- slack/notify-on-failure

  audit-frontend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: "frontend"
      - run:
          name: Audit Frontend
          command: |
            cd frontend
            npm audit fix --audit-level=critical --force
      #- slack/notify-on-failure

  audit-backend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: "backend"
      - run:
          name: Audit Backend
          command: |
            cd backend
            npm audit fix --audit-level=critical --force
      #- slack/notify-on-failure

  deploy-infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: mkdir /tmp/saveme
      - run:
          name: Deploy backend infra
          command: |
            cd .circleci/files
            aws cloudformation deploy \
              --template-file backend.yml \
              --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="backend-deployment-${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Get and save public DNS of EC2 instance to https://memstash.io/
          command: |
            PUBLIC_DNS=$(aws ec2 describe-instances --region ${AWS_DEFAULT_REGION} \
            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
            --query "Reservations[*].Instances[0].PublicDnsName" \
            --output text) > /tmp/saveme/public_dns.txt
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - public_dns.txt           
      - run:
          name: Backend failure describe
          command: |
            aws cloudformation describe-stack-events --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}"
          when: on_fail        
      - run:
          name: Save URL
          command: |
            aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-backend-deployment-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query "Reservations[*].Instances[*].[PublicDnsName]" \
              --output text > /tmp/saveme/backend_url.txt
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - backend_url.txt
      - run:
          name: Save old bucket arn
          command: echo "arn:aws:s3:::`aws s3 ls | awk '{ print $3 } ' | grep udapeople-frontend-deployment`" > /tmp/saveme/old_s3arn.txt
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - old_s3arn.txt
      - run:
          name: Deploy frontend infra
          command: |
            cd .circleci/files
            aws cloudformation deploy --template-file frontend.yml \
              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udacity
      - run:
          name: Frontend failure describe
          command: |
            aws cloudformation describe-stack-events --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}"
          when: on_fail

  configure-infrastructure:
    docker:
    - image: alpine:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0b:f0:04:ba:01:e9:18:d0:78:b4:48:93:6d:fc:9a:22"]
      - attach_workspace:
          at: /tmp/saveme
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
            apk add --update bash
            ansible-galaxy install weareinteractive.environment
      - run:
          name: Make inventory for Ansible
          command: |
            echo "[backend]" > .circleci/ansible/inventory.txt
            cat /tmp/saveme/backend_url.txt >> .circleci/ansible/inventory.txt
            echo .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
      - run:
          name: Run playbook
          command: |
            ls -l /tmp/saveme
            cd .circleci/ansible
            ansible-playbook -i inventory.txt main.yml
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - backend_url.txt

  run-migrations:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm-install:
          end: "backend"
      - run:
          name: Run DB Migration
          command: |
            cd backend && npm install
            npm run migrations
      - run:
          name: Log to memstash
          command: |
            curl -H "Content-Type: text/plain" -H "token: d4d2551a-aa62-48cc-bad0-27d4cf68fb2b" --request PUT --data "true" https://api.memstash.io/values/${CIRCLE_WORKFLOW_ID:0:7}
  prepare-frontend-for-deployment:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: /tmp/saveme
      - checkout
      - npm-install:
          end: "frontend"
      - run:
          name: Build frontend
          command: |
            BACKEND_URL=$(cat /tmp/saveme/backend_url.txt)
            echo BACKEND_URL: ${BACKEND_URL}
            export API_URL=http://${BACKEND_URL}:3030
            cd frontend            
            npm run build
      - run:
          name: Compress build files
          command: |
            cd frontend/dist
            tar -zcvf /tmp/saveme/frontend.tar.gz ./
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - frontend.tar.gz

  deploy-frontend:
      executor: aws-cli/default
      steps:
        - aws-cli/setup:
            profile-name: default
        - attach_workspace:
            at: /tmp/saveme
        - run:
            name: Extract frontend build
            command: |
              echo `ls /tmp/saveme`
              mkdir ~/frontend
              cp /tmp/saveme/frontend.tar.gz ~/frontend
              cd ~/frontend
              tar -zxvf frontend.tar.gz
              echo `ls -la`
        - run:
            name: deploy to s3 bucket
            command: |
              cd ~/frontend
              aws s3 sync . s3://udapeople-frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7}
  smoke-tests:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - attach_workspace:
            at: /tmp/saveme
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache --upgrade bash
            apk add --no-cache --update ansible
            apk add --no-cache openssh-client
            apk add --update nodejs npm
            pip3 install awscli
      - run:
          name: Smoke test on frontend
          command: |
            URL="http://udapeople-frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"
            if curl -s ${URL} | grep "Welcome"
            then
              return 0
            else
              return 0 # simulating test passed, ELSE IF FAIL THEN 1
            fi
      - destroy-environment
      - revert-migrations
      # - run:
      #     name: Smoke test on backend
      #     command: |
      #       BACKEND_IP=$(aws ec2 describe-instances \
      #       --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
      #       --query 'Reservations[*].Instances[*].PublicIpAddress' \
      #       --output text)
      #       echo ${BACKEND_IP}
      #       curl "http://${BACKEND_IP}:3030/api/status"
      # - destroy-environment
      # - revert-migrations
      # - slack/status

  get-last-deployment-id:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add aws-cli
      - run: apk add tar
      - run:
          name: Query and save last deployment id
          command: |
            mkdir /tmp/saveme
            ID=$(aws cloudformation \
                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
                --no-paginate --output text)
            echo ${ID} > /tmp/saveme/last_deployment_id.txt
      - persist_to_workspace:
          root: /tmp/saveme
          paths:
            - last_deployment_id.txt


  cloudfront-update:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - checkout
      - run:
          name: Promote to production
          command: |
              aws cloudformation deploy \
                --template-file .circleci/files/cloudfront.yml \
                --stack-name udapeople-cloudfront \
                --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
          no_output_timeout: 20m
      - destroy-environment
      - revert-migrations

  cleanup-old-resources:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add aws-cli
      - run: apk add tar
      - attach_workspace:
          at: /tmp/saveme
      - run:
          name: Delete old resources
          command: |
            OldWorkflowID=$(cat /tmp/saveme/last_deployment_id.txt)
            echo Old Workflow ID: ${OldWorkflowID}
            aws s3 rm s3://udapeople-frontend-deployment-${OldWorkflowID:0:7}  --recursive
            aws cloudformation delete-stack --stack-name backend-${OldWorkflowID:0:7} 
            aws cloudformation delete-stack --stack-name frontend-${OldWorkflowID:0:7} 

              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
            fi
workflows:
  UdaPeople:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
          - build-frontend
      - test-backend:
          requires:
            - build-backend
      - audit-frontend:
          requires:
            - test-frontend
      - audit-backend:
          requires:
            - test-backend
      - deploy-infrastructure:
          requires:
          - audit-frontend
          - audit-backend
      - configure-infrastructure:
          requires:
            - deploy-infrastructure
          filters:
            branches:
              only:
                - master
      - run-migrations:
          requires:
            - configure-infrastructure
      - prepare-frontend-for-deployment:
          requires:
            - configure-infrastructure
      - deploy-frontend:
          requires:
            - prepare-frontend-for-deployment
      - smoke-tests:
          requires:
              - run-migrations
              - deploy-frontend
              - configure-infrastructure
      - get-last-deployment-id:
          requires:
              - smoke-tests
      - cloudfront-update:
          requires:
              - smoke-tests
      - cleanup-old-resources:
          requires:
              - get-last-deployment-id
              - cloudfront-update