version: 2.1
jobs:
  backend:
    docker:
      - image: circleci/node:10.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run lint
      - run: cd backend && npm run build

  frontend:
    docker:
      - image: circleci/node:10.8.0

    working_directory: ~/Projects/udapeople
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint
      - run: cd frontend && npm run build
      - run: cd frontend && npm run test:coverage

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend