#Created by Rafael Castro Gonzalez
version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build 

  frontend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run build

  test-backend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm i
      - run: cd backend && npm run test
      - store_test_results:
          path: test-results

  test-frontend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd frontend && npm i && npm install request --save
      - run: cd frontend && npm run test
      - store_test_results:
          path: test-results

  analyze-backend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm audit fix --audit-level=critical --force
      - run: cd backend && npm audit --audit-level=critical


  analyze-frontend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd frontend && npm audit fix --audit-level=critical --force
      - run: cd frontend && npm audit --audit-level=critical


  create_infrastructure_backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file backend.yml \
              --stack-name backend-udapeople


  create_infrastructure_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure frontend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file frontend.yml \
              --stack-name frontend-udapeople


  create_cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure cloudfront infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file cloudfront.yml \
              --stack-name frontend-udapeople             
workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend
      - test-backend:
          requires:
            - backend
      - test-frontend:
          requires:
            - frontend
      - analyze-backend:
          requires:
            - test-backend
      - analyze-frontend:
          requires:
            - test-frontend
      - create_infrastructure_backend:
          requires:
            - analyze-backend
      - create_infrastructure_frontend:
          requires:
            - create_infrastructure_backend
      - create_cloudfront:
          requires:
            - create_infrastructure_frontend     