version: 2.1
jobs:
  backend:
    docker:
      - image: circleci/node:10.8.0

    working_directory: ~/Projects/udapeople/backend

    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run build

  frontend:
    docker:
      - image: circleci/node:10.8.0

    working_directory: ~/Projects/udapeople/frontend
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test:coverage

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend