#Created by Rafael Castro
version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build 

  frontend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run build

  test-backend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd backend && npm i
      - run: cd backend && npm run test
      - store_test_results:
          path: test-results

  test-frontend:
    docker:
      - image: circleci/node:13.8.0

    working_directory: ~/Projects/udapeople

    steps:
      - checkout
      - run: cd frontend && npm i && npm install request --save
      - run: cd frontend && npm run test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend
      - test-backend:
          requires:
            - backend
      - test-frontend:
          requires:
            - frontend